spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/events
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8180/realms/events

server:
  servlet:
    context-path: /api/v1
  error:
    include-message: always

springdoc:
  api-docs:
    path: /api-docs
  oAuthFlow:
    authorizationUrl: ${spring.security.oauth2.resource-server.jwt.issuer-uri}/protocol/openid-connect/auth
    tokenUrl: ${spring.security.oauth2.resource-server.jwt.issuer-uri}/protocol/openid-connect/token